version: '3'

services:
  jenkins:
    image: claudiocesarjr/jenkins:latest
    container_name: jenkins
    build: 
      context: .
    ports:
      - 80:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      #- ./jenkins-date:/var/jenkins_home